[project]
name = "mp42mp3"
version = "0.1.0"
description = "A Python tool to convert MP4 videos to MP3 audio files using MoviePy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moviepy>=1.0.3",
]